// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-mWn0UHgtWgith5O4Uc-K4AjrG-N4Ls',
    appId: '1:75650730688:web:515f4c5e88559273cb3b25',
    messagingSenderId: '75650730688',
    projectId: 'chatapplication-69687',
    authDomain: 'chatapplication-69687.firebaseapp.com',
    storageBucket: 'chatapplication-69687.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfiy9whPOCCaLnxxG4Pnal_aln2f-iYfg',
    appId: '1:75650730688:android:f244edea9c395130cb3b25',
    messagingSenderId: '75650730688',
    projectId: 'chatapplication-69687',
    storageBucket: 'chatapplication-69687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeYd8CvIf9ys7l6oj_MnJs805Sg3fwIM',
    appId: '1:75650730688:ios:371c0e2068014200cb3b25',
    messagingSenderId: '75650730688',
    projectId: 'chatapplication-69687',
    storageBucket: 'chatapplication-69687.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTeYd8CvIf9ys7l6oj_MnJs805Sg3fwIM',
    appId: '1:75650730688:ios:3eb44520221e7ae3cb3b25',
    messagingSenderId: '75650730688',
    projectId: 'chatapplication-69687',
    storageBucket: 'chatapplication-69687.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
